`timescale 1ns/1ps
//Author: Generated by yaaaay!! dpgen
module test/output2(a, b, c, z, x);
	input 	signed	[31:0]	a;
	input 	signed	[31:0]	b;
	input 	signed	[31:0]	c;
	output 	signed	[31:0]	z;
	output 	signed	[31:0]	x;
	wire 	signed	[31:0]	d;
	wire 	signed	[31:0]	e;
	wire 	signed	[31:0]	f;
	wire 	signed	[31:0]	g;
	wire 	signed	[31:0]	h;
	wire 	signed	[0:0]	dLTe;
	wire 	signed	[0:0]	dEQe;
	wire 	signed	[31:0]	zwire;
	wire 	signed	[31:0]	xwire;
	add #(.DATAWIDTH(32))	ADD0(a, b, d);
 	add #(.DATAWIDTH(32))	ADD1(a, c, e);
 	sub #(.DATAWIDTH(32))	SUB2(a, b, f);
 	comp #(.DATAWIDTH(32))	COMP_EQ3(.a(d), .b(e), .eq(dEQe));
	comp #(.DATAWIDTH(32))	COMP_LT4(.a(d), .b(e), .lt(dLTe));
	mux2x1 #(.DATAWIDTH(32))	MUX2x15(.sel(dLTe), .a(d), .b(e), .d(g));
	mux2x1 #(.DATAWIDTH(32))	MUX2x16(.sel(dEQe), .a(g), .b(f), .d(h));
	shl #(.DATAWIDTH(32))	SHL7(g, {31'd0,dLTe}, xwire);
 	shr #(.DATAWIDTH(32))	SHR8(h, {31'd0,dEQe}, zwire);
 	assign x = xwire;
	assign z = zwire;
endmodule