`timescale 1ns/1ps
//Author: Generated by yaaaay!! dpgen
module test/output3(a, b, c, d, e, f, g, h, sa, avg);
	input 	signed	[15:0]	a;
	input 	signed	[15:0]	b;
	input 	signed	[15:0]	c;
	input 	signed	[15:0]	d;
	input 	signed	[15:0]	e;
	input 	signed	[15:0]	f;
	input 	signed	[15:0]	g;
	input 	signed	[15:0]	h;
	input 	signed	[7:0]	sa;
	output 	signed	[15:0]	avg;
	wire 	signed	[31:0]	l00;
	wire 	signed	[31:0]	l01;
	wire 	signed	[31:0]	l02;
	wire 	signed	[31:0]	l03;
	wire 	signed	[31:0]	l10;
	wire 	signed	[31:0]	l11;
	wire 	signed	[31:0]	l2;
	wire 	signed	[31:0]	l2div2;
	wire 	signed	[31:0]	l2div4;
	wire 	signed	[31:0]	l2div8;
	add #(.DATAWIDTH(32))	ADD0(a[15]?{{16{1'd1}},a}:{{16{1'd0}},a}, b[15]?{{16{1'd1}},b}:{{16{1'd0}},b}, l00);
 	add #(.DATAWIDTH(32))	ADD1(c[15]?{{16{1'd1}},c}:{{16{1'd0}},c}, d[15]?{{16{1'd1}},d}:{{16{1'd0}},d}, l01);
 	add #(.DATAWIDTH(32))	ADD2(e[15]?{{16{1'd1}},e}:{{16{1'd0}},e}, f[15]?{{16{1'd1}},f}:{{16{1'd0}},f}, l02);
 	add #(.DATAWIDTH(32))	ADD3(g[15]?{{16{1'd1}},g}:{{16{1'd0}},g}, h[15]?{{16{1'd1}},h}:{{16{1'd0}},h}, l03);
 	add #(.DATAWIDTH(32))	ADD4(l00, l01, l10);
 	add #(.DATAWIDTH(32))	ADD5(l02, l03, l11);
 	add #(.DATAWIDTH(32))	ADD6(l10, l11, l2);
 	shr #(.DATAWIDTH(32))	SHR7(l2, sa[7]?{{24{1'd1}},sa}:{{24{1'd0}},sa}, l2div2);
 	shr #(.DATAWIDTH(32))	SHR8(l2div2, sa[7]?{{24{1'd1}},sa}:{{24{1'd0}},sa}, l2div4);
 	shr #(.DATAWIDTH(32))	SHR9(l2div4, sa[7]?{{24{1'd1}},sa}:{{24{1'd0}},sa}, l2div8);
 	assign avg = l2div8[15:0];
endmodule