`timescale 1ns/1ps
//Author: Generated by yaaaay!! dpgen
module test/output8(a, b, c, zero, z);
	input 	signed	[63:0]	a;
	input 	signed	[63:0]	b;
	input 	signed	[63:0]	c;
	input 	signed	[63:0]	zero;
	output 	signed	[63:0]	z;
	wire 	signed	[63:0]	e;
	wire 	signed	[63:0]	f;
	wire 	signed	[63:0]	g;
	wire 	signed	[63:0]	zwire;
	wire 	signed	[0:0]	gEQz;
	dec #(.DATAWIDTH(64))	DEC0(a, e);
 	inc #(.DATAWIDTH(64))	INC1(c, f);
 	mod #(.DATAWIDTH(64))	MOD2(a, c, g);
 	comp #(.DATAWIDTH(64))	COMP_EQ3(.a(g), .b(zero), .eq(gEQz));
	mux2x1 #(.DATAWIDTH(64))	MUX2x14(.sel(gEQz), .a(e), .b(f), .d(zwire));
	assign z = zwire;
endmodule