`timescale 1ns/1ps
//Author: Generated by yaaaay!! dpgen
module test/output7(a, b, c, d, zero, z);
	input 	signed	[63:0]	a;
	input 	signed	[63:0]	b;
	input 	signed	[63:0]	c;
	input 	signed	[63:0]	d;
	input 	signed	[63:0]	zero;
	output 	signed	[63:0]	z;
	wire 	signed	[63:0]	e;
	wire 	signed	[63:0]	f;
	wire 	signed	[63:0]	g;
	wire 	signed	[63:0]	zwire;
	wire 	signed	[0:0]	gEQz;
	div #(.DATAWIDTH(64))	DIV0(a, b, e);
 	div #(.DATAWIDTH(64))	DIV1(c, d, f);
 	mod #(.DATAWIDTH(64))	MOD2(a, b, g);
 	comp #(.DATAWIDTH(64))	COMP_EQ3(.a(g), .b(zero), .eq(gEQz));
	mux2x1 #(.DATAWIDTH(64))	MUX2x14(.sel(gEQz), .a(e), .b(f), .d(zwire));
	assign z = zwire;
endmodule