`timescale 1ns/1ps
//Author: Generated by yaaaay!! dpgen
module test/output5(a, b, c, z, x, clk, rst);
	input 	signed	[63:0]	a;
	input 	signed	[63:0]	b;
	input 	signed	[63:0]	c;
	output 	signed	[31:0]	z;
	output 	signed	[31:0]	x;
	wire 	signed	[63:0]	d;
	wire 	signed	[63:0]	e;
	wire 	signed	[63:0]	f;
	wire 	signed	[63:0]	g;
	wire 	signed	[63:0]	h;
	wire 	signed	[0:0]	dLTe;
	wire 	signed	[0:0]	dEQe;
	wire 	signed	[63:0]	xrin;
	wire 	signed	[63:0]	zrin;
	wire 	signed	[63:0]	greg;
	wire 	signed	[63:0]	hreg;
	input 	clk, rst;
	add #(.DATAWIDTH(64))	ADD0(a, b, d);
 	add #(.DATAWIDTH(64))	ADD1(a, c, e);
 	sub #(.DATAWIDTH(64))	SUB2(a, b, f);
 	comp #(.DATAWIDTH(64))	COMP_EQ3(.a(d), .b(e), .eq(dEQe));
	comp #(.DATAWIDTH(64))	COMP_LT4(.a(d), .b(e), .lt(dLTe));
	mux2x1 #(.DATAWIDTH(64))	MUX2x15(.sel(dLTe), .a(d), .b(e), .d(g));
	mux2x1 #(.DATAWIDTH(64))	MUX2x16(.sel(dEQe), .a(g), .b(f), .d(h));
	register #(.DATAWIDTH(64))	REG7(clk, rst, g, greg);
	register #(.DATAWIDTH(64))	REG8(clk, rst, h, hreg);
	shl #(.DATAWIDTH(64))	SHL9(hreg, {63'd0,dLTe}, xrin);
 	shr #(.DATAWIDTH(64))	SHR10(greg, {63'd0,dEQe}, zrin);
 	assign x = xrin[31:0];
	assign z = zrin[31:0];
endmodule