`timescale 1ns/1ps
//Author: Generated by yaaaay!! dpgen
module C:\Users\Andres\Documents\GitHub\PROJECT_ATHENA\dpgen\test\output(a, b, c, z, x);
	input 	signed	[7:0]	a;
	input 	signed	[7:0]	b;
	input 	signed	[7:0]	c;
	output 	signed	[7:0]	z;
	output 	signed	[15:0]	x;
	wire 	signed	[7:0]	d;
	wire 	signed	[7:0]	e;
	wire 	signed	[15:0]	f;
	wire 	signed	[0:0]	g;
	wire 	signed	[15:0]	xwire;
	add #(.DATAWIDTH(8))	ADD0(a, b, d);
 	add #(.DATAWIDTH(8))	ADD1(a, c, e);
 	comp #(.DATAWIDTH(8))	COMP_GT2(.a(d), .b(e), .gt(g));
	mux2x1 #(.DATAWIDTH(8))	MUX2x13(.sel(g), .a(d), .b(e), .d(z));
	mul #(.DATAWIDTH(16))	MUL4(a[7]?{{8{1'd1}},a}:{{8{1'd0}},a}, c[7]?{{8{1'd1}},c}:{{8{1'd0}},c}, f);
 	sub #(.DATAWIDTH(16))	SUB5(f, d[7]?{{8{1'd1}},d}:{{8{1'd0}},d}, xwire);
 	assign x = xwire;
endmodule